# set offset of drones

size: 9

drone_0:
  x: 1.0
  y: 0.0
  z: 0.0

drone_1:
  x: -1.0
  y: 0.0
  z: 0.0

drone_2:
  x: 1.0
  y: -1.0
  z: 0.0

drone_3:
  x: -1.0
  y: 1.0
  z: 0.0

drone_4:
  x: -1.0
  y: -1.0
  z: 0.0

drone_5:
  x: 1.0
  y: 1.0
  z: 0.0

drone_6:
  x: 0.0
  y: 0.0
  z: 0.0

drone_7:
  x: 0.0
  y: 1.0
  z: 0.0

drone_8:
  x: 0.0
  y: -1.0
  z: 0.0